### ISSUE TITLE
@example output funky indents

### ISSUE THREAD

**Issue by joshlasdin** [gruntjs/grunt-contrib-yuidoc#27]
Not sure if I'm doing something wrong here, but all of my code examples using the @example tag get pushed a bunch of indents after the first line: http://d.pr/i/jply

Any way to fix this? Here's my example code:
```
    /**
     * Creates a new user
     *
     * @method create
     * @for sdk.user
     * @param data {object}
     * @param data.email {string}
     * @param data.first_name {string}
     * @param data.last_name {string}
     * @param data.metadata {object}
     * @param data.tags {array}
     * @param callback
     * @param callback.err {string}
     * @param callback.response {object} [User object](/classes/object.user.html)
     * @example
     *
     *      sdk.user.create({
     *          first_name: 'Ron',
     *          last_name: 'Swanson',
     *          email: 'ron@pawneeparksdept.gov'
     *      }, function (err, response) {
     *          if (!err) {
     *              // User created
     *          }
     *      });
     */
```

I thought at first it might be the theme I'm using, but having the same issue with the default theme. Thanks!

**Comment by vladikoff** [comment]
Cannot reproduce with the default theme:
## Result
![image](https://cloud.githubusercontent.com/assets/128755/5760054/0d49eece-9ca0-11e4-93d0-4799aa8b24e4.png)
## Code
```js

    /**
     * Manage tokens on the server. Implements {{#crossLink "TokenAPI"}}{{/crossLink}}.
     * @property token
     * @type {Object}
     *
     * @example
     *     var fxaRelierClient = new FxaRelierClient('<client_id>', {
     *       clientSecret: <client_secret>
     *     });
     *     fxaRelierClient.token.tradeCode(<code>)
     *       .then(function (token) {
     *         // do something awesome with the token like get
     *         // profile information. See profile.
     *       });
     */
    this.token = new TokenAPI(clientId, options);

    /**
     * Fetch profile information on the server. Implements {{#crossLink "ProfileAPI"}}{{/crossLink}}.
     * @property profile
     * @type {Object}
     *
     * @example
     *     var fxaRelierClient = new FxaRelierClient('<client_id>', {
     *       clientSecret: <client_secret>
     *     });
     *     fxaRelierClient.token.tradeCode(<code>)
     *       .then(function (token) {
     *         return fxaRelierClient.fetch(token);
     *       })
     *       .then(function (profile) {
     *         // display some profile info.
     *       });
     */
    this.profile = new ProfileAPI(clientId, options);
```

**Comment by shameister** [comment]
Hey there,

we are experiancing the same issue with the default template.
Is there any solution?

Our doc:

	/**
	 * Ermöglicht das registrieren eigener Chatbefehle.
	 * In einem Channel kann nur eine <code>App</code> laufen, die einen bestimmten Chatbefehl nutzt.
	 * Versucht eine zweite <code>App</code> einen Chatbefehl zu registrieren, den eine andere
	 * App bereits nutzt, so wird ein Fehler geloggt und die App startet nicht bzw. fährt herunter.
	 * 
	 * @property chatCommands
	 * 
	 * @example
	 *     this.chatCommands =
	 *     {
	 *        foo: function(user, param, command)
	 *        {
	 *           // Jemand im Chat hat /foo eingegeben.
	 *        }
	 *     }
	 */

![bildschirmfoto 2015-03-10 um 22 14 06](https://cloud.githubusercontent.com/assets/98413/6585552/db9b8786-c772-11e4-939f-e510eb732f86.png)

**Comment by Bizarrus** [comment]
Same problem here, tested with both themes (`standard` and `simple`).

@vladikoff which version are you using? The last build didn't work with your *examples* 
![eample](https://cloud.githubusercontent.com/assets/1371300/6586746/634f65cc-c77c-11e4-9ff1-1d3f4a68756d.PNG)

**Comment by joshlasdin** [comment]
Sorry to say I never got it working. Just left the funky indents and kept going. Meant to come back to it at some point and dig deeper. 😒
